### ISSUE TITLE
specfit.EQW() not working? Try this.

### ISSUE THREAD

**Issue by alejocosmico** [munazzaalam/PHEW#2]
The EQW() function has the parameter "continuum" set to 0.5. This parameter should not be set to a specific value, because it tells EQW() to use that value as the baseline value. Better, thus, to just get rid of this parameter in the calling of the function.

**Comment by munazzaalam** [comment]
Thanks! I'm also in the process of modifying this code for pyspeckit 0.17, so stay tuned.
